# Generated by Django 5.0.2 on 2024-02-19 05:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="name",
            new_name="customer_name",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="created",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="description",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total",
        ),
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 5, 34, 17, 924629, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="InvoiceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
    ]
